name: Lint Code Base

on:
  schedule:
    - cron: '0 1 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm ci
    - name: Run ESLint
      run: npm run lint
