name: Lint Code Base

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '28 5 * * 1'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm ci
    - name: Run ESLint
      run: npm run lint
    - name: Build TSC
      run: tsc --build
