name: Build Typescript
on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '28 5 * * 1'
jobs:
  build-push:
    runs-on: ubuntu-latest
    name: Builds Typescript
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJs
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 16
      - name: Install dependancies
        run: npm ci
      - name: Building Typescript
        uses: alexthemaster/action-build-typescript@master # check the releases tab on the right for versions (looks like this: v1.0.0)
              # use this if you want the sharpest of cutting edges (can and probably WILL break from time to time)
              # uses: alexthemaster/action-build-typescript@master
        with:
            pushToBranch: true # optional; can either be true or false | defaults to false
            branch: 'dist' # optional; the name of the branch the action should push the compiled code to | defaults to dist
            githubToken: ${{ secrets.GITHUB_TOKEN }} # required if you use the pushToBranch option
