name: Build Typescript
on: 
    push: 
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout project
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2.1.4
              with:
                node-version: 12
            - name: Build and push
              uses: alexthemaster/action-build-typescript@v1.0.0
              with:
                pushToBranch: true # optional; can either be true or false | defaults to false
                branch: 'dist' # optional; the name of the branch the action should push the compiled code to | defaults to dist
                githubToken: ${{ secrets.token }} # required if you use the pushToBranch option
